Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/xenial64"
 config.vm.hostname = "ewout.be"
 config.vm.network :private_network, ip: "192.168.68.8"
 config.vm.network :forwarded_port, guest: 80, host: 1234, host_ip: "127.0.0.1", auto_correct: true
 config.vm.provision "shell", path: ".provision/bootstrap.sh"
end